spring:
  main:
    lazy-initialization: true
  application:
    name: purse-ai
  config:
    import: 
      - optional:classpath:application-ai.yml
      - optional:classpath:application-saving.properties

server:
  port: 8080

jwt:
  secret: 12345678901234567890123456789012
  expiration: 86400000 # 24 hours in milliseconds

logging:
  config: classpath:logback-spring.xml
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: DEBUG
    org.springframework.ai: DEBUG 